# Generated by Django 5.2.16 on 2026-07-28 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=60)),
                ('anios_experiencia', models.IntegerField()),
                ('idiomas_hablados', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('ciudad', models.CharField(max_length=30)),
                ('anio_fund', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_exhibicion', models.CharField(max_length=30)),
                ('duracion_meses', models.IntegerField()),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tematica', models.CharField(max_length=30)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibiciones', to='museo.guia')),
            ],
        ),
        migrations.AddField(
            model_name='guia',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='museo.museo'),
        ),
    ]
